name: prim
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.1.31=hf0a4a13_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.1=py310h7f4e7e6_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - freetype=2.13.3=h1d14073_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - kiwisolver=1.4.8=py310h313beb8_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=31_h10e41b3_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libcxx=19.1.7=ha82da77_0
  - libdeflate=1.23=hec38601_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - liblzma=5.6.4=h39f12f2_0
  - liblzma-devel=5.6.4=h39f12f2_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libpng=1.6.47=h3783ad8_0
  - libsqlite=3.42.0=hb31c410_0
  - libtiff=4.7.0=h551f018_3
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=19.1.7=hdb05f8b_0
  - matplotlib-base=3.10.1=py310hadbac3a_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h5e97a16_3
  - openjpeg=2.5.3=h8a3d83b_0
  - openssl=3.4.1=h81ee809_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py310hfd37619_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pillow=11.1.0=py310h61efb56_0
  - pip=25.0.1=pyh8b19718_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pytest=8.3.5=pyhd8ed1ab_0
  - python=3.10.0=h43b31ca_3_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=5_cp310
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1d1bf99_2
  - scikit-learn=1.6.1=py310h48c93d9_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=75.8.2=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.42.0=h203b68d_0
  - statsmodels=0.14.4=py310hae04be4_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py310h078409c_0
  - unicodedata2=16.0.0=py310h078409c_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.6.4=h9a6d368_0
  - xz-gpl-tools=5.6.4=h9a6d368_0
  - xz-tools=5.6.4=h39f12f2_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.8
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - alembic==1.14.1
      - altair==5.5.0
      - annotated-types==0.7.0
      - anthropic==0.49.0
      - anyio==4.8.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - autogen-agentchat==0.5.5
      - autogen-core==0.5.5
      - autogen-ext==0.5.5
      - azure-ai-documentintelligence==1.0.0
      - azure-ai-inference==1.0.0b9
      - azure-core==1.32.0
      - azure-identity==1.20.0
      - beautifulsoup4==4.13.3
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cobble==0.1.4
      - colorlog==6.9.0
      - cryptography==44.0.2
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - email-validator==2.2.0
      - et-xmlfile==2.0.0
      - fastapi==0.115.11
      - fastapi-cli==0.0.7
      - ffmpy==0.5.0
      - filelock==3.17.0
      - flask==3.1.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.24.0
      - gradio-client==1.8.0
      - greenlet==3.1.1
      - groovy==0.1.2
      - h11==0.14.0
      - html2text==2024.2.26
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.30.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - jiter==0.8.2
      - json-schema-to-pydantic==0.2.4
      - jsonref==1.1.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - lightgbm==4.6.0
      - llvmlite==0.44.0
      - loguru==0.7.3
      - lxml==5.3.1
      - mako==1.3.9
      - mammoth==1.9.0
      - markdown-it-py==3.0.0
      - markdownify==1.0.0
      - markitdown==0.0.1a5
      - markupsafe==3.0.2
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msal==1.31.1
      - msal-extensions==1.2.0
      - multidict==6.1.0
      - narwhals==1.34.0
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==2.1.3
      - olefile==0.47
      - openai==1.65.2
      - openpyxl==3.1.5
      - opentelemetry-api==1.30.0
      - optuna==4.2.1
      - orjson==3.10.16
      - pathvalidate==3.2.3
      - pdfminer-six==20240706
      - playwright==1.50.0
      - plotly==6.0.1
      - portalocker==2.10.1
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - psycopg==3.2.5
      - puremagic==1.28
      - pyarrow==19.0.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.8.1
      - pydeck==0.9.1
      - pydub==0.25.1
      - pyee==12.1.1
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - python-pptx==1.0.2
      - pytz==2025.1
      - pyyaml==6.0.2
      - rdkit==2024.9.5
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rich-toolkit==0.13.2
      - rpds-py==0.24.0
      - ruff==0.11.4
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scipy==1.15.2
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - speechrecognition==3.14.1
      - sqlalchemy==2.0.38
      - sqlmodel==0.0.23
      - starlette==0.46.0
      - streamlit==1.44.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - toml==0.10.2
      - tomlkit==0.13.2
      - torch==2.6.0
      - torch-geometric==2.6.1
      - tqdm==4.67.1
      - transformers==4.51.0
      - typer==0.15.2
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - umap-learn==0.5.7
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - watchfiles==1.0.4
      - websockets==15.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xlrd==2.0.1
      - xlsxwriter==3.2.2
      - yarl==1.18.3
      - youtube-transcript-api==0.6.3
      - zipp==3.21.0